sudo: required
services:
  - docker

before_install:
  - docker build -t nuge/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nuge/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-2-258526555030"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "AKIATYMLCFOLN7P42KGA"
  secret_access_key: 
    secure: "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"
